version = 0.1

[default.deploy.parameters]
stack_name = "trust-safety-orch-dev"
resolve_s3 = true
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"dev\" UseRedis=\"false\""
tags = "Project=\"TrustSafetyOrchestration\" Team=\"TrustAndSafety\" Environment=\"dev\""

[default.build.parameters]
use_container = false
parallel = true
